---
name: Release
'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'geerlingguy.homebrew'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'geerlingguy.homebrew'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: "TODO: Release process TBD."
        run: "echo 'not implemented'"
